// client-angular/src/app/features/clients/pages/client-list/client-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { ToastModule } from 'primeng/toast';
import { MessageService } from 'primeng/api';
import { ClientService } from '../../../../core/services/client.service';
import { Client } from '../../../../models';
import { LoadingSpinnerComponent } from '../../../../shared/components/loading-spinner/loading-spinner.component';
import { EmptyStateComponent } from '../../../../shared/components/empty-state/empty-state.component';

@Component({
  selector: 'app-client-list',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, TableModule, ButtonModule, DialogModule, InputTextModule, ToastModule, LoadingSpinnerComponent, EmptyStateComponent],
  providers: [MessageService],
  template: `
    <app-loading *ngIf="loading"></app-loading>
    <div *ngIf="!loading">
      <div class="flex items-center justify-between mb-8">
        <div><h1 class="text-2xl font-bold text-gray-900">Clients</h1><p class="text-sm text-gray-500 mt-1">{{clients.length}} total clients</p></div>
        <p-button icon="pi pi-plus" label="Add Client" (click)="showAdd=true"></p-button>
      </div>
      <app-empty-state *ngIf="clients.length===0" icon="pi-users" message="No clients yet. Add your first client."></app-empty-state>
      <div class="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden" *ngIf="clients.length>0">
        <p-table [value]="clients" styleClass="p-datatable-sm">
          <ng-template pTemplate="header"><tr><th>Name</th><th>Contact</th><th>Email</th><th>Phone</th></tr></ng-template>
          <ng-template pTemplate="body" let-c>
            <tr class="hover:bg-gray-50">
              <td><a [routerLink]="['/clients',c.id]" class="text-sm font-medium text-brand-600 hover:text-brand-700">{{c.name}}</a></td>
              <td class="text-sm text-gray-700">{{c.contact_name||'-'}}</td>
              <td class="text-sm text-gray-700">{{c.email||'-'}}</td>
              <td class="text-sm text-gray-700">{{c.phone||'-'}}</td>
            </tr>
          </ng-template>
        </p-table>
      </div>
    </div>
    <p-dialog header="Add Client" [(visible)]="showAdd" [modal]="true" [style]="{width:'450px'}">
      <div class="space-y-4">
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Company Name *</label><input pInputText [(ngModel)]="nc.name" class="w-full"/></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Contact Name</label><input pInputText [(ngModel)]="nc.contact_name" class="w-full"/></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Email</label><input pInputText [(ngModel)]="nc.email" class="w-full"/></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Phone</label><input pInputText [(ngModel)]="nc.phone" class="w-full"/></div>
      </div>
      <ng-template pTemplate="footer">
        <p-button label="Cancel" [text]="true" (click)="showAdd=false"></p-button>
        <p-button label="Add Client" icon="pi pi-plus" [disabled]="!nc.name" (click)="add()" [loading]="adding"></p-button>
      </ng-template>
    </p-dialog>
    <p-toast></p-toast>
  `
})
export class ClientListComponent implements OnInit {
  clients: Client[] = [];
  loading = true;
  showAdd = false;
  adding = false;
  nc = { name: '', contact_name: '', email: '', phone: '' };

  constructor(private svc: ClientService, private msg: MessageService) {}
  ngOnInit() { this.load(); }
  load() { this.svc.getAll().subscribe({ next: d => { this.clients = d; this.loading = false; }, error: () => this.loading = false }); }
  add() {
    this.adding = true;
    this.svc.create(this.nc).subscribe({
      next: () => { this.showAdd = false; this.adding = false; this.nc = { name: '', contact_name: '', email: '', phone: '' }; this.msg.add({ severity: 'success', summary: 'Added' }); this.load(); },
      error: () => { this.adding = false; this.msg.add({ severity: 'error', summary: 'Error' }); }
    });
  }
}

// client/src/pages/ClientList.jsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Users } from 'lucide-react';
import { api } from '../lib/api';
import Modal from '../components/Modal';

export default function ClientList() {
  const [clients, setClients] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showAdd, setShowAdd] = useState(false);
  const [addForm, setAddForm] = useState({ name: '', contact_name: '', email: '', phone: '' });
  const [adding, setAdding] = useState(false);

  useEffect(() => {
    loadClients();
  }, []);

  const loadClients = () => {
    api.get('/clients')
      .then((data) => setClients(Array.isArray(data) ? data : data.data || []))
      .catch(() => setClients([]))
      .finally(() => setLoading(false));
  };

  const handleAdd = async () => {
    setAdding(true);
    try {
      await api.post('/clients', addForm);
      setShowAdd(false);
      setAddForm({ name: '', contact_name: '', email: '', phone: '' });
      loadClients();
    } catch (err) {
      alert('Failed to add client: ' + err.message);
    } finally {
      setAdding(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-400 text-sm">Loading clients...</div>
      </div>
    );
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Clients</h1>
          <p className="text-sm text-gray-500 mt-1">{clients.length} total clients</p>
        </div>
        <button
          onClick={() => setShowAdd(true)}
          className="inline-flex items-center gap-2 bg-brand-600 text-white px-4 py-2.5 rounded-lg text-sm font-medium hover:bg-brand-700 transition-colors"
        >
          <Plus className="w-4 h-4" />
          Add Client
        </button>
      </div>

      {clients.length === 0 ? (
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm px-6 py-16 text-center">
          <Users className="w-10 h-10 text-gray-300 mx-auto mb-3" />
          <p className="text-sm text-gray-500">No clients yet. Add your first client to get started.</p>
        </div>
      ) : (
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden">
          <table className="w-full">
            <thead>
              <tr className="border-b border-gray-200 bg-gray-50">
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Name</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Contact</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Email</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Phone</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {clients.map((client) => (
                <tr key={client.id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-6 py-4">
                    <Link to={`/clients/${client.id}`} className="text-sm font-medium text-brand-600 hover:text-brand-700">
                      {client.name || client.org_name}
                    </Link>
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-700">{client.contact_name || '-'}</td>
                  <td className="px-6 py-4 text-sm text-gray-700">{client.email || client.contact_email || '-'}</td>
                  <td className="px-6 py-4 text-sm text-gray-700">{client.phone || client.contact_phone || '-'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <Modal open={showAdd} onClose={() => setShowAdd(false)} title="Add Client">
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Company Name *</label>
            <input
              type="text"
              value={addForm.name}
              onChange={(e) => setAddForm((prev) => ({ ...prev, name: e.target.value }))}
              className="w-full border border-gray-300 rounded-lg px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
              placeholder="Client company name"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Contact Name</label>
            <input
              type="text"
              value={addForm.contact_name}
              onChange={(e) => setAddForm((prev) => ({ ...prev, contact_name: e.target.value }))}
              className="w-full border border-gray-300 rounded-lg px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
              placeholder="Primary contact name"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
            <input
              type="email"
              value={addForm.email}
              onChange={(e) => setAddForm((prev) => ({ ...prev, email: e.target.value }))}
              className="w-full border border-gray-300 rounded-lg px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
              placeholder="contact@company.com"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Phone</label>
            <input
              type="tel"
              value={addForm.phone}
              onChange={(e) => setAddForm((prev) => ({ ...prev, phone: e.target.value }))}
              className="w-full border border-gray-300 rounded-lg px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
              placeholder="+44 ..."
            />
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <button
              onClick={() => setShowAdd(false)}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              onClick={handleAdd}
              disabled={adding || !addForm.name}
              className="px-4 py-2 text-sm font-medium text-white bg-brand-600 rounded-lg hover:bg-brand-700 disabled:opacity-40"
            >
              {adding ? 'Adding...' : 'Add Client'}
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
