// client/src/pages/ProjectList.jsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Search, FolderKanban } from 'lucide-react';
import { api } from '../lib/api';
import { formatGBP } from '../components/CurrencyDisplay';
import StatusBadge from '../components/StatusBadge';

export default function ProjectList() {
  const [projects, setProjects] = useState([]);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/projects')
      .then((data) => setProjects(Array.isArray(data) ? data : data.data || []))
      .catch(() => setProjects([]))
      .finally(() => setLoading(false));
  }, []);

  const filtered = projects.filter((p) => {
    const name = (p.event_name || p.name || '').toLowerCase();
    return name.includes(search.toLowerCase());
  });

  return (
    <div>
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Projects</h1>
          <p className="text-sm text-gray-500 mt-1">{projects.length} total projects</p>
        </div>
        <Link
          to="/projects/new"
          className="inline-flex items-center gap-2 bg-brand-600 text-white px-4 py-2.5 rounded-lg text-sm font-medium hover:bg-brand-700 transition-colors"
        >
          <Plus className="w-4 h-4" />
          New Project
        </Link>
      </div>

      {/* Search */}
      <div className="mb-6">
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input
            type="text"
            placeholder="Search projects..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
          />
        </div>
      </div>

      {loading ? (
        <div className="flex items-center justify-center h-64">
          <div className="text-gray-400 text-sm">Loading projects...</div>
        </div>
      ) : filtered.length === 0 ? (
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm px-6 py-16 text-center">
          <FolderKanban className="w-10 h-10 text-gray-300 mx-auto mb-3" />
          <p className="text-sm text-gray-500">
            {search ? 'No projects match your search.' : 'No projects yet. Create your first project.'}
          </p>
        </div>
      ) : (
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden">
          <table className="w-full">
            <thead>
              <tr className="border-b border-gray-200 bg-gray-50">
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Project</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Client</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Event Date</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Status</th>
                <th className="text-right px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Total Cost</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {filtered.map((project) => (
                <tr key={project.id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-6 py-4">
                    <Link to={`/projects/${project.id}`} className="text-sm font-medium text-brand-600 hover:text-brand-700">
                      {project.event_name || project.name || 'Untitled'}
                    </Link>
                    {project.venue_city && (
                      <p className="text-xs text-gray-500 mt-0.5">{project.venue_city}</p>
                    )}
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-700">{project.client_name || '-'}</td>
                  <td className="px-6 py-4 text-sm text-gray-700">
                    {project.event_date || '-'}
                  </td>
                  <td className="px-6 py-4">
                    <StatusBadge status={project.status_name} />
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-900 font-medium text-right">
                    {formatGBP(project.total_client_cost || 0)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// client-angular/src/app/features/projects/pages/project-list/project-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { ToastModule } from 'primeng/toast';
import { ConfirmationService, MessageService } from 'primeng/api';
import { ProjectService } from '../../../../core/services/project.service';
import { Project } from '../../../../core/models';
import { StatusBadgeComponent } from '../../../../shared/components/status-badge/status-badge.component';
import { GbpPipe } from '../../../../shared/pipes/gbp.pipe';
import { LoadingSpinnerComponent } from '../../../../shared/components/loading-spinner/loading-spinner.component';
import { EmptyStateComponent } from '../../../../shared/components/empty-state/empty-state.component';

@Component({
  selector: 'app-project-list',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, TableModule, ButtonModule, InputTextModule, ConfirmDialogModule, ToastModule, StatusBadgeComponent, GbpPipe, LoadingSpinnerComponent, EmptyStateComponent],
  providers: [ConfirmationService, MessageService],
  template: `
    <app-loading *ngIf="loading"></app-loading>
    <div *ngIf="!loading">
      <div class="flex items-center justify-between mb-8">
        <div><h1 class="text-2xl font-bold text-gray-900">Projects</h1>
          <p class="text-sm text-gray-500 mt-1">{{ projects.length }} total projects</p></div>
        <a routerLink="/projects/new"><p-button icon="pi pi-plus" label="New Project"></p-button></a>
      </div>
      <div class="mb-6 max-w-md">
        <span class="p-input-icon-left w-full"><i class="pi pi-search"></i>
          <input pInputText [(ngModel)]="searchTerm" placeholder="Search projects..." class="w-full" (input)="filter()" /></span>
      </div>
      <app-empty-state *ngIf="filtered.length === 0" icon="pi-folder" [message]="searchTerm ? 'No projects match your search.' : 'No projects yet. Create your first project.'"></app-empty-state>
      <div class="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden" *ngIf="filtered.length > 0">
        <p-table [value]="filtered" [paginator]="filtered.length > 20" [rows]="20" styleClass="p-datatable-sm">
          <ng-template pTemplate="header"><tr>
            <th pSortableColumn="event_name">Project <p-sortIcon field="event_name"></p-sortIcon></th>
            <th>Client</th><th>Event Date</th><th>Venue</th><th>Status</th>
            <th class="text-right">Total Cost</th><th class="text-center" style="width:80px">Actions</th>
          </tr></ng-template>
          <ng-template pTemplate="body" let-p>
            <tr class="hover:bg-gray-50">
              <td><a [routerLink]="['/projects', p.id]" class="text-sm font-medium text-brand-600 hover:text-brand-700">{{ p.event_name || p.name || 'Untitled' }}</a>
                <div class="text-xs text-gray-500" *ngIf="p.venue_city">{{ p.venue_city }}</div></td>
              <td class="text-sm text-gray-700">{{ p.client_name || '-' }}</td>
              <td class="text-sm text-gray-700">{{ p.event_date || '-' }}</td>
              <td class="text-sm text-gray-700">{{ p.venue_name || '-' }}</td>
              <td><app-status-badge [status]="p.status_name"></app-status-badge></td>
              <td class="text-right text-sm font-medium">{{ p.total_client_cost | gbp }}</td>
              <td class="text-center">
                <a [routerLink]="['/projects', p.id]"><p-button icon="pi pi-eye" [rounded]="true" [text]="true" severity="info" size="small"></p-button></a>
                <p-button icon="pi pi-trash" [rounded]="true" [text]="true" severity="danger" size="small" (click)="confirmDelete(p)"></p-button>
              </td>
            </tr>
          </ng-template>
        </p-table>
      </div>
    </div>
    <p-confirmDialog></p-confirmDialog><p-toast></p-toast>
  `
})
export class ProjectListComponent implements OnInit {
  projects: Project[] = [];
  filtered: Project[] = [];
  searchTerm = '';
  loading = true;

  constructor(private svc: ProjectService, private confirm: ConfirmationService, private msg: MessageService) {}
  ngOnInit() { this.load(); }

  load() {
    this.svc.getAll().subscribe({
      next: d => { this.projects = d; this.filtered = d; this.loading = false; },
      error: () => { this.loading = false; }
    });
  }

  filter() {
    const t = this.searchTerm.toLowerCase();
    this.filtered = this.projects.filter(p =>
      (p.event_name || p.name || '').toLowerCase().includes(t) ||
      (p.client_name || '').toLowerCase().includes(t)
    );
  }

  confirmDelete(p: Project) {
    this.confirm.confirm({
      message: `Delete "${p.event_name || p.name}"?`, header: 'Confirm', icon: 'pi pi-exclamation-triangle',
      accept: () => this.svc.delete(p.id).subscribe({ next: () => { this.msg.add({ severity: 'success', summary: 'Deleted' }); this.load(); } })
    });
  }
}
