// client/src/pages/ProjectDetail.jsx
import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Plus, Send, Loader2 } from 'lucide-react';
import { api } from '../lib/api';
import { formatGBP } from '../components/CurrencyDisplay';
import StatusBadge from '../components/StatusBadge';
import Modal from '../components/Modal';

const TABS = ['Overview', 'Categories', 'Estimates', 'Messages'];

export default function ProjectDetail() {
  const { id } = useParams();
  const [project, setProject] = useState(null);
  const [categories, setCategories] = useState([]);
  const [estimates, setEstimates] = useState([]);
  const [messages, setMessages] = useState([]);
  const [activeTab, setActiveTab] = useState('Overview');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadProject();
  }, [id]);

  const loadProject = async () => {
    setLoading(true);
    try {
      const [proj, ests, msgs] = await Promise.all([
        api.get(`/projects/${id}`),
        api.get(`/estimates?project_id=${id}`).catch(() => []),
        api.get(`/messages?project_id=${id}`).catch(() => []),
      ]);
      setProject(proj);
      setCategories(proj.project_categories || []);
      setEstimates(Array.isArray(ests) ? ests : ests.data || []);
      setMessages(Array.isArray(msgs) ? msgs : msgs.data || []);
    } catch (err) {
      console.error('Failed to load project', err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-400 text-sm">Loading project...</div>
      </div>
    );
  }

  if (!project) {
    return (
      <div className="text-center py-16">
        <p className="text-gray-500">Project not found.</p>
        <Link to="/projects" className="text-brand-600 hover:text-brand-700 text-sm mt-2 inline-block">Back to Projects</Link>
      </div>
    );
  }

  return (
    <div>
      {/* Header */}
      <div className="mb-6">
        <Link to="/projects" className="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700 mb-4">
          <ArrowLeft className="w-4 h-4" />
          Back to Projects
        </Link>
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">{project.event_name || 'Untitled Project'}</h1>
            <div className="flex items-center gap-3 mt-2 text-sm text-gray-500">
              {project.venue_name && <span>{project.venue_name}</span>}
              {project.venue_city && <span>· {project.venue_city}</span>}
              {project.event_date && <span>· {project.event_date}</span>}
            </div>
          </div>
          <StatusBadge status={project.status_name} />
        </div>
      </div>

      {/* Tabs */}
      <div className="border-b border-gray-200 mb-6">
        <nav className="flex gap-6">
          {TABS.map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`pb-3 text-sm font-medium border-b-2 transition-colors ${
                activeTab === tab
                  ? 'border-brand-600 text-brand-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700'
              }`}
            >
              {tab}
            </button>
          ))}
        </nav>
      </div>

      {/* Tab Content */}
      {activeTab === 'Overview' && <OverviewTab project={project} />}
      {activeTab === 'Categories' && <CategoriesTab projectId={id} categories={categories} onRefresh={loadProject} />}
      {activeTab === 'Estimates' && <EstimatesTab estimates={estimates} />}
      {activeTab === 'Messages' && <MessagesTab projectId={id} messages={messages} onRefresh={loadProject} />}
    </div>
  );
}

function OverviewTab({ project }) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      {/* Event Details */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6">
        <h3 className="text-sm font-semibold text-gray-900 mb-4">Event Details</h3>
        <dl className="space-y-3">
          <DetailRow label="Event Name" value={project.event_name} />
          <DetailRow label="Event Date" value={project.event_date || '-'} />
          <DetailRow label="Venue" value={project.venue_name} />
          <DetailRow label="City" value={project.venue_city} />
          <DetailRow label="Address" value={project.venue_address} />
          <DetailRow label="Guest Count" value={project.guest_count} />
          <DetailRow label="Tier" value={project.tier} />
        </dl>
      </div>

      {/* Stand Info */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6">
        <h3 className="text-sm font-semibold text-gray-900 mb-4">Stand Configuration</h3>
        <dl className="space-y-3">
          <DetailRow label="Size" value={project.stand_size} />
          <DetailRow label="Area" value={(() => { const area = parseFloat(project.stand_width_m || 0) * parseFloat(project.stand_depth_m || 0); return area > 0 ? `${area} sqm` : '-'; })()} />
          <DetailRow label="Type" value={project.stand_type?.replace('_', ' ')} />
        </dl>
      </div>

      {/* Brief */}
      {project.raw_brief_text && (
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6 lg:col-span-2">
          <h3 className="text-sm font-semibold text-gray-900 mb-4">Brief</h3>
          <p className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">{project.raw_brief_text}</p>
        </div>
      )}

      {/* Financials */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-6 lg:col-span-2">
        <h3 className="text-sm font-semibold text-gray-900 mb-4">Financial Summary</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
          <div>
            <p className="text-xs text-gray-500 uppercase tracking-wide">Budget</p>
            <p className="text-lg font-bold text-gray-900 mt-1">{formatGBP(project.project_budget || 0)}</p>
          </div>
          <div>
            <p className="text-xs text-gray-500 uppercase tracking-wide">Margin</p>
            <p className="text-lg font-bold text-gray-900 mt-1">{project.default_margin_pct || 0}%</p>
          </div>
          <div>
            <p className="text-xs text-gray-500 uppercase tracking-wide">Contingency</p>
            <p className="text-lg font-bold text-gray-900 mt-1">{project.default_contingency_pct || 0}%</p>
          </div>
          <div>
            <p className="text-xs text-gray-500 uppercase tracking-wide">Total Client Cost</p>
            <p className="text-lg font-bold text-brand-600 mt-1">{formatGBP(project.total_client_cost || 0)}</p>
          </div>
        </div>
      </div>
    </div>
  );
}

function CategoriesTab({ projectId, categories, onRefresh }) {
  const [showAdd, setShowAdd] = useState(false);
  const [addForm, setAddForm] = useState({ category_name: '', requirement_brief: '' });
  const [adding, setAdding] = useState(false);

  const handleAdd = async () => {
    setAdding(true);
    try {
      await api.post('/project-categories', { project_id: projectId, name: addForm.category_name, requirement_brief: addForm.requirement_brief });
      setShowAdd(false);
      setAddForm({ category_name: '', requirement_brief: '' });
      onRefresh();
    } catch (err) {
      alert('Failed to add category: ' + err.message);
    } finally {
      setAdding(false);
    }
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-semibold text-gray-900">Cost Breakdown by Category</h3>
        <button
          onClick={() => setShowAdd(true)}
          className="inline-flex items-center gap-2 bg-brand-600 text-white px-3 py-2 rounded-lg text-xs font-medium hover:bg-brand-700 transition-colors"
        >
          <Plus className="w-3.5 h-3.5" />
          Add Category
        </button>
      </div>

      {categories.length === 0 ? (
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm px-6 py-12 text-center">
          <p className="text-sm text-gray-500">No categories yet. Add a category to start building your estimate.</p>
        </div>
      ) : (
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 bg-gray-50">
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Category</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Brief</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Ballpark</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Base Cost</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Contingency</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Subtotal</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Margin</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Net Cost</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">VAT</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Client Cost</th>
                <th className="text-center px-4 py-3 text-xs font-medium text-gray-500 uppercase tracking-wide">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {categories.map((cat) => (
                <tr key={cat.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3 font-medium text-gray-900">
                    <div className="flex items-center gap-2">
                      {cat.icon && <span className="text-base">{cat.icon}</span>}
                      {cat.category_name || cat.name}
                    </div>
                  </td>
                  <td className="px-4 py-3 text-gray-600 max-w-[180px] truncate">{cat.requirement_brief || '-'}</td>
                  <td className="px-4 py-3 text-right text-gray-700">{formatGBP(cat.ballpark_cost || 0)}</td>
                  <td className="px-4 py-3 text-right text-gray-700">{formatGBP(cat.base_cost || 0)}</td>
                  <td className="px-4 py-3 text-right text-gray-700">{formatGBP(cat.contingency_amount || 0)}</td>
                  <td className="px-4 py-3 text-right text-gray-700">{formatGBP(cat.subtotal || 0)}</td>
                  <td className="px-4 py-3 text-right text-gray-700">{formatGBP(cat.margin_amount || 0)}</td>
                  <td className="px-4 py-3 text-right text-gray-700">{formatGBP(cat.net_cost || 0)}</td>
                  <td className="px-4 py-3 text-right text-gray-700">{formatGBP(cat.vat_amount || 0)}</td>
                  <td className="px-4 py-3 text-right font-medium text-gray-900">{formatGBP(cat.client_cost || 0)}</td>
                  <td className="px-4 py-3 text-center">
                    <StatusBadge status={cat.status_name || 'pending'} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <Modal open={showAdd} onClose={() => setShowAdd(false)} title="Add Category">
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Category Name</label>
            <input
              type="text"
              value={addForm.category_name}
              onChange={(e) => setAddForm((prev) => ({ ...prev, category_name: e.target.value }))}
              className="w-full border border-gray-300 rounded-lg px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
              placeholder="e.g. Graphics, AV, Furniture"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Requirement Brief</label>
            <textarea
              value={addForm.requirement_brief}
              onChange={(e) => setAddForm((prev) => ({ ...prev, requirement_brief: e.target.value }))}
              rows={3}
              className="w-full border border-gray-300 rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500 resize-y"
              placeholder="Describe what's needed for this category..."
            />
          </div>
          <div className="flex justify-end gap-3 pt-2">
            <button
              onClick={() => setShowAdd(false)}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              onClick={handleAdd}
              disabled={adding || !addForm.category_name}
              className="px-4 py-2 text-sm font-medium text-white bg-brand-600 rounded-lg hover:bg-brand-700 disabled:opacity-40"
            >
              {adding ? 'Adding...' : 'Add Category'}
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
}

function EstimatesTab({ estimates }) {
  return (
    <div>
      <h3 className="text-sm font-semibold text-gray-900 mb-4">Estimates</h3>
      {estimates.length === 0 ? (
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm px-6 py-12 text-center">
          <p className="text-sm text-gray-500">No estimates generated yet.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {estimates.map((est) => (
            <div key={est.id} className="bg-white rounded-lg border border-gray-200 shadow-sm p-5">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-semibold text-gray-900">Version {est.version || est.id}</p>
                  <p className="text-xs text-gray-500 mt-1">
                    Created {est.created_at ? new Date(est.created_at).toLocaleDateString('en-GB') : '-'}
                  </p>
                </div>
                <div className="flex items-center gap-4">
                  <div className="text-right">
                    <p className="text-xs text-gray-500">Total Value</p>
                    <p className="text-sm font-bold text-gray-900">{formatGBP(est.total_value || 0)}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs text-gray-500">Balls Cost</p>
                    <p className="text-sm font-bold text-purple-600">{est.balls_cost || 0} balls</p>
                  </div>
                  <StatusBadge status={est.status_name || 'draft'} />
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function MessagesTab({ projectId, messages, onRefresh }) {
  const [newMsg, setNewMsg] = useState('');
  const [sending, setSending] = useState(false);

  const handleSend = async () => {
    if (!newMsg.trim()) return;
    setSending(true);
    try {
      await api.post('/messages', { project_id: projectId, body: newMsg, direction: 'outbound', subject: 'Message' });
      setNewMsg('');
      onRefresh();
    } catch (err) {
      alert('Failed to send message: ' + err.message);
    } finally {
      setSending(false);
    }
  };

  return (
    <div>
      <h3 className="text-sm font-semibold text-gray-900 mb-4">Messages</h3>
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
        <div className="max-h-96 overflow-y-auto p-6 space-y-4">
          {messages.length === 0 ? (
            <p className="text-sm text-gray-400 text-center py-8">No messages yet. Start the conversation.</p>
          ) : (
            messages.map((msg) => (
              <div key={msg.id} className={`flex gap-3 ${msg.direction === 'outbound' ? 'flex-row-reverse' : ''}`}>
                <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${msg.direction === 'outbound' ? 'bg-brand-100' : 'bg-gray-100'}`}>
                  <span className={`text-xs font-semibold ${msg.direction === 'outbound' ? 'text-brand-600' : 'text-gray-600'}`}>
                    {(msg.sender_name || msg.role || 'U').charAt(0).toUpperCase()}
                  </span>
                </div>
                <div className={`flex-1 min-w-0 ${msg.direction === 'outbound' ? 'text-right' : ''}`}>
                  <div className={`flex items-center gap-2 ${msg.direction === 'outbound' ? 'justify-end' : ''}`}>
                    <span className="text-sm font-medium text-gray-900">{msg.sender_name || msg.role || 'User'}</span>
                    <span className="text-xs text-gray-400">
                      {msg.created_at ? new Date(msg.created_at).toLocaleString('en-GB') : ''}
                    </span>
                  </div>
                  <p className="text-sm text-gray-700 mt-1 whitespace-pre-wrap">{msg.body}</p>
                </div>
              </div>
            ))
          )}
        </div>
        <div className="border-t border-gray-200 p-4">
          <div className="flex gap-3">
            <input
              type="text"
              value={newMsg}
              onChange={(e) => setNewMsg(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && handleSend()}
              placeholder="Type a message..."
              className="flex-1 border border-gray-300 rounded-lg px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
            />
            <button
              onClick={handleSend}
              disabled={sending || !newMsg.trim()}
              className="inline-flex items-center gap-2 px-4 py-2.5 bg-brand-600 text-white rounded-lg text-sm font-medium hover:bg-brand-700 disabled:opacity-40 transition-colors"
            >
              {sending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function DetailRow({ label, value }) {
  return (
    <div className="flex justify-between">
      <dt className="text-sm text-gray-500">{label}</dt>
      <dd className="text-sm font-medium text-gray-900 capitalize">{value || '-'}</dd>
    </div>
  );
}

// client-angular/src/app/features/projects/pages/project-detail/project-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { TabViewModule } from 'primeng/tabview';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { InputTextareaModule } from 'primeng/inputtextarea';
import { LucideAngularModule, ArrowLeft, Sparkles } from 'lucide-angular';
import { ProjectService } from '../../../../core/services/project.service';
import { EstimateService } from '../../../../core/services/estimate.service';
import { MessageService } from '../../../../core/services/message.service';
import { ProjectCategoryService } from '../../../../core/services/project-category.service';
import { Project, ProjectCategory, Estimate, Message } from '../../../../models';
import { StatusBadgeComponent } from '../../../../shared/components/status-badge/status-badge.component';
import { GbpPipe } from '../../../../shared/pipes/gbp.pipe';
import { LoadingSpinnerComponent } from '../../../../shared/components/loading-spinner/loading-spinner.component';
import { EmptyStateComponent } from '../../../../shared/components/empty-state/empty-state.component';

@Component({
  selector: 'app-project-detail',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, LucideAngularModule, TabViewModule, TableModule, ButtonModule, DialogModule, InputTextModule, InputTextareaModule, StatusBadgeComponent, GbpPipe, LoadingSpinnerComponent, EmptyStateComponent],
  template: `
    <app-loading *ngIf="loading"></app-loading>
    <div *ngIf="!loading && !project" class="text-center py-16"><p class="text-gray-500">Project not found.</p>
      <a routerLink="/projects" style="color:var(--theme-accent);font-size:var(--text-sm);" class="mt-2 inline-block">Back to Projects</a></div>
    <div *ngIf="!loading && project">
      <div class="mb-6">
        <a routerLink="/projects" class="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700 mb-4"><lucide-icon name="arrow-left" [size]="12"></lucide-icon> Back to Projects</a>
        <div class="flex items-start justify-between">
          <div><h1 class="text-2xl font-bold text-gray-900">{{project.event_name||project.name}}</h1>
            <div class="flex items-center gap-3 mt-2 text-sm text-gray-500">
              <span *ngIf="project.venue_name">{{project.venue_name}}</span>
              <span *ngIf="project.venue_city">· {{project.venue_city}}</span>
              <span *ngIf="project.event_date">· {{project.event_date}}</span>
            </div>
          </div>
          <app-status-badge [status]="project.status_name"></app-status-badge>
        </div>
      </div>
      <p-tabView>
        <p-tabPanel header="Overview">
          <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-4">
            <div class="bg-white rounded-lg border border-gray-200 shadow-sm p-6">
              <h3 class="text-sm font-semibold text-gray-900 mb-4">Event Details</h3>
              <dl class="space-y-3">
                <div class="flex justify-between" *ngFor="let r of eventRows"><dt class="text-sm text-gray-500">{{r.l}}</dt><dd class="text-sm font-medium text-gray-900 capitalize">{{r.v||'-'}}</dd></div>
              </dl>
            </div>
            <div class="bg-white rounded-lg border border-gray-200 shadow-sm p-6">
              <h3 class="text-sm font-semibold text-gray-900 mb-4">Stand Configuration</h3>
              <dl class="space-y-3">
                <div class="flex justify-between"><dt class="text-sm text-gray-500">Size</dt><dd class="text-sm font-medium text-gray-900 capitalize">{{project.stand_size||'-'}}</dd></div>
                <div class="flex justify-between"><dt class="text-sm text-gray-500">Area</dt><dd class="text-sm font-medium text-gray-900">{{standArea ? standArea+' m²' : '-'}}</dd></div>
                <div class="flex justify-between"><dt class="text-sm text-gray-500">Type</dt><dd class="text-sm font-medium text-gray-900">{{(project.stand_type||'-').replace('_',' ')}}</dd></div>
              </dl>
            </div>
            <div *ngIf="project.raw_brief_text" class="bg-white rounded-lg border border-gray-200 shadow-sm p-6 lg:col-span-2">
              <h3 class="text-sm font-semibold text-gray-900 mb-4">Brief</h3>
              <p class="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">{{project.raw_brief_text}}</p>
            </div>
            <div class="bg-white rounded-lg border border-gray-200 shadow-sm p-6 lg:col-span-2">
              <h3 class="text-sm font-semibold text-gray-900 mb-4">Financial Summary</h3>
              <div class="grid grid-cols-2 md:grid-cols-4 gap-6">
                <div><p class="text-xs text-gray-500 uppercase">Budget</p><p class="text-lg font-bold text-gray-900 mt-1">{{project.project_budget|gbp}}</p></div>
                <div><p class="text-xs text-gray-500 uppercase">Margin</p><p class="text-lg font-bold text-gray-900 mt-1">{{project.default_margin_pct||0}}%</p></div>
                <div><p class="text-xs text-gray-500 uppercase">Contingency</p><p class="text-lg font-bold text-gray-900 mt-1">{{project.default_contingency_pct||0}}%</p></div>
                <div><p class="text-xs text-gray-500 uppercase">Total Client Cost</p><p class="text-lg font-bold text-brand-600 mt-1">{{project.total_client_cost|gbp}}</p></div>
              </div>
            </div>
          </div>
        </p-tabPanel>
        <p-tabPanel header="Categories">
          <div class="mt-4">
            <div class="flex items-center justify-between mb-4">
              <h3 class="text-sm font-semibold text-gray-900">Cost Breakdown by Category</h3>
              <p-button icon="pi pi-plus" label="Add Category" size="small" (click)="showAddCat=true"></p-button>
            </div>
            <app-empty-state *ngIf="cats.length===0" icon="pi-list" message="No categories yet."></app-empty-state>
            <div class="bg-white rounded-lg border border-gray-200 shadow-sm overflow-x-auto" *ngIf="cats.length>0">
              <p-table [value]="cats" styleClass="p-datatable-sm">
                <ng-template pTemplate="header"><tr>
                  <th>Category</th><th>Brief</th><th class="text-right">Ballpark</th><th class="text-right">Base</th>
                  <th class="text-right">Contingency</th><th class="text-right">Subtotal</th><th class="text-right">Margin</th>
                  <th class="text-right">Net</th><th class="text-right">VAT</th><th class="text-right">Client Cost</th><th class="text-center">Status</th>
                </tr></ng-template>
                <ng-template pTemplate="body" let-c>
                  <tr><td class="font-medium">{{c.name}}</td><td class="text-gray-600 max-w-[180px] truncate">{{c.requirement_brief||'-'}}</td>
                    <td class="text-right">{{c.ballpark_cost|gbp}}</td><td class="text-right">{{c.base_cost|gbp}}</td>
                    <td class="text-right">{{c.contingency_amount|gbp}}</td><td class="text-right">{{c.subtotal|gbp}}</td>
                    <td class="text-right">{{c.margin_amount|gbp}}</td><td class="text-right">{{c.net_cost|gbp}}</td>
                    <td class="text-right">{{c.vat_amount|gbp}}</td><td class="text-right font-medium">{{c.client_cost|gbp}}</td>
                    <td class="text-center"><app-status-badge [status]="c.status_name||'pending'"></app-status-badge></td>
                  </tr>
                </ng-template>
              </p-table>
            </div>
          </div>
        </p-tabPanel>
        <p-tabPanel header="Estimates">
          <div class="mt-4">
            <app-empty-state *ngIf="ests.length===0" icon="pi-file" message="No estimates yet."></app-empty-state>
            <div class="space-y-3" *ngIf="ests.length>0">
              <div *ngFor="let e of ests" class="bg-white rounded-lg border border-gray-200 shadow-sm p-5">
                <div class="flex items-center justify-between">
                  <div><p class="text-sm font-semibold text-gray-900">{{e.name||'Version '+e.version}}</p><p class="text-xs text-gray-500 mt-1">{{e.created_at|date:'d MMM yyyy'}}</p></div>
                  <div class="flex items-center gap-4">
                    <div class="text-right"><p class="text-xs text-gray-500">Total Value</p><p class="text-sm font-bold">{{e.total_value|gbp}}</p></div>
                    <div class="text-right"><p class="text-xs text-gray-500">Balls</p><p class="text-sm font-bold text-purple-600">{{e.balls_cost}}</p></div>
                    <app-status-badge [status]="e.status_name||'draft'"></app-status-badge>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </p-tabPanel>
        <p-tabPanel header="Messages">
          <div class="mt-4">
            <div class="bg-white rounded-lg border border-gray-200 shadow-sm">
              <div class="max-h-96 overflow-y-auto p-6 space-y-4">
                <p *ngIf="msgs.length===0" class="text-sm text-gray-400 text-center py-8">No messages yet.</p>
                <div *ngFor="let m of msgs" [class]="m.direction==='outbound'?'flex justify-end':'flex justify-start'">
                  <div [class]="'max-w-[70%] rounded-lg p-3 '+(m.direction==='outbound'?'bg-brand-50':'bg-gray-50')">
                    <div class="flex items-center gap-2 mb-1"><span class="text-xs font-medium text-gray-900">{{m.sender_name||'User'}}</span>
                      <span class="text-xs text-gray-400">{{m.created_at|date:'d MMM HH:mm'}}</span></div>
                    <p class="text-sm text-gray-700">{{m.body}}</p>
                  </div>
                </div>
              </div>
              <div class="border-t border-gray-200 p-4"><div class="flex gap-3">
                <input pInputText [(ngModel)]="newMsg" placeholder="Type a message..." class="flex-1" (keyup.enter)="sendMsg()"/>
                <p-button icon="pi pi-send" [disabled]="!newMsg.trim()||sending" (click)="sendMsg()" [loading]="sending"></p-button>
              </div></div>
            </div>
          </div>
        </p-tabPanel>
      </p-tabView>
    </div>
    <p-dialog header="Add Category" [(visible)]="showAddCat" [modal]="true" [style]="{width:'450px'}">
      <div class="space-y-4">
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Category Name</label><input pInputText [(ngModel)]="newCat.name" class="w-full"/></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Requirement Brief</label><textarea pInputTextarea [(ngModel)]="newCat.brief" [rows]="3" class="w-full"></textarea></div>
      </div>
      <ng-template pTemplate="footer">
        <p-button label="Cancel" [text]="true" (click)="showAddCat=false"></p-button>
        <p-button label="Add" icon="pi pi-plus" [disabled]="!newCat.name" (click)="addCat()" [loading]="addingCat"></p-button>
      </ng-template>
    </p-dialog>
  `
})
export class ProjectDetailComponent implements OnInit {
  readonly icons = { ArrowLeft, Sparkles };
  project: Project | null = null;
  cats: ProjectCategory[] = [];
  ests: Estimate[] = [];
  msgs: Message[] = [];
  loading = true;
  newMsg = '';
  sending = false;
  showAddCat = false;
  addingCat = false;
  newCat = { name: '', brief: '' };
  private pid = '';

  get standArea(): number { return +(this.project?.stand_width_m || 0) * +(this.project?.stand_depth_m || 0); }
  get eventRows() {
    const p = this.project!;
    return [
      { l: 'Event Name', v: p.event_name }, { l: 'Event Date', v: p.event_date },
      { l: 'Venue', v: p.venue_name }, { l: 'City', v: p.venue_city },
      { l: 'Guest Count', v: p.guest_count }, { l: 'Tier', v: p.tier },
    ];
  }

  constructor(private route: ActivatedRoute, private projSvc: ProjectService, private estSvc: EstimateService, private msgSvc: MessageService, private pcSvc: ProjectCategoryService) {}

  ngOnInit() {
    this.pid = this.route.snapshot.paramMap.get('id') || '';
    this.loadAll();
  }

  loadAll() {
    this.loading = true;
    this.projSvc.getById(this.pid).subscribe({ next: p => { this.project = p; this.cats = p.project_categories || []; this.loading = false; }, error: () => this.loading = false });
    this.estSvc.getByProject(this.pid).subscribe({ next: d => this.ests = d, error: () => {} });
    this.msgSvc.getByProject(this.pid).subscribe({ next: d => this.msgs = d, error: () => {} });
  }

  sendMsg() {
    if (!this.newMsg?.trim()) return;
    this.sending = true;
    this.msgSvc.create({ project_id: this.pid, body: this.newMsg, direction: 'outbound', subject: 'Message' }).subscribe({
      next: () => { this.newMsg = ''; this.sending = false; this.msgSvc.getByProject(this.pid).subscribe(d => this.msgs = d); },
      error: () => this.sending = false
    });
  }

  addCat() {
    this.addingCat = true;
    this.pcSvc.create({ project_id: this.pid, name: this.newCat.name, requirement_brief: this.newCat.brief }).subscribe({
      next: () => { this.showAddCat = false; this.addingCat = false; this.newCat = { name: '', brief: '' }; this.loadAll(); },
      error: () => this.addingCat = false
    });
  }
}
