// client/src/pages/ProjectCreate.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ChevronLeft, ChevronRight, Check, Sparkles, Loader2 } from 'lucide-react';
import { api } from '../lib/api';

const STEPS = ['Tier', 'Event Details', 'Stand Config', 'Brief', 'Financials'];

const TIERS = [
  {
    key: 'starter',
    name: 'Starter',
    description: 'Perfect for small exhibitions and pop-up stands. Basic shell scheme setup with essential furnishings.',
    color: 'border-gray-300 bg-gray-50',
    selectedColor: 'border-brand-600 bg-brand-50 ring-2 ring-brand-600',
  },
  {
    key: 'professional',
    name: 'Professional',
    description: 'Full custom stand build with graphics, lighting and AV. Ideal for mid-size trade shows.',
    color: 'border-gray-300 bg-gray-50',
    selectedColor: 'border-brand-600 bg-brand-50 ring-2 ring-brand-600',
  },
  {
    key: 'premium',
    name: 'Premium',
    description: 'Bespoke design with premium materials, interactive displays, and full project management.',
    color: 'border-gray-300 bg-gray-50',
    selectedColor: 'border-brand-600 bg-brand-50 ring-2 ring-brand-600',
  },
];

const STAND_SIZES = [
  { key: 'small', label: 'Small', sqm: 9, desc: '3m x 3m' },
  { key: 'medium', label: 'Medium', sqm: 18, desc: '6m x 3m' },
  { key: 'large', label: 'Large', sqm: 36, desc: '6m x 6m' },
  { key: 'xl', label: 'XL', sqm: 72, desc: '12m x 6m' },
  { key: 'custom', label: 'Custom', sqm: 0, desc: 'Enter size' },
];

export default function ProjectCreate() {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [submitting, setSubmitting] = useState(false);
  const [parsing, setParsing] = useState(false);
  const [parsedBrief, setParsedBrief] = useState(null);

  const [form, setForm] = useState({
    tier: '',
    event_name: '',
    event_date: '',
    venue_name: '',
    venue_city: '',
    venue_address: '',
    guest_count: '',
    stand_size: '',
    stand_sqm: '',
    stand_type: 'shell_scheme',
    raw_brief_text: '',
    project_budget: '',
    margin_pct: '20',
    contingency_pct: '5',
    vat_pct: '20',
  });

  const set = (field, value) => setForm((prev) => ({ ...prev, [field]: value }));

  const canNext = () => {
    switch (step) {
      case 0: return !!form.tier;
      case 1: return !!form.event_name && !!form.event_date;
      case 2: return (form.stand_size && form.stand_size !== 'custom') || (form.stand_size === 'custom' && form.stand_sqm > 0);
      case 3: return true;
      case 4: return true;
      default: return true;
    }
  };

  const handleParseBrief = async () => {
    if (!form.raw_brief_text.trim()) return;
    setParsing(true);
    try {
      const result = await api.post('/ai/parse-brief', { raw_brief_text: form.raw_brief_text });
      setParsedBrief(result);
    } catch (err) {
      alert('Failed to parse brief: ' + err.message);
    } finally {
      setParsing(false);
    }
  };

  const handleSubmit = async () => {
    setSubmitting(true);
    try {
      const selectedSize = STAND_SIZES.find((s) => s.key === form.stand_size);
      let standWidthM, standDepthM;
      if (form.stand_size === 'custom') {
        const customSqm = parseFloat(form.stand_sqm) || 0;
        standWidthM = Math.sqrt(customSqm);
        standDepthM = Math.sqrt(customSqm);
      } else if (selectedSize) {
        const dims = selectedSize.desc.split('x').map((d) => parseFloat(d.trim()));
        standWidthM = dims[0] || 0;
        standDepthM = dims[1] || 0;
      } else {
        standWidthM = 0;
        standDepthM = 0;
      }

      const payload = {
        name: form.event_name,
        tier: form.tier,
        event_name: form.event_name,
        event_date: form.event_date,
        venue_name: form.venue_name,
        venue_city: form.venue_city,
        venue_address: form.venue_address,
        guest_count: parseInt(form.guest_count) || 0,
        stand_size: form.stand_size,
        stand_width_m: standWidthM,
        stand_depth_m: standDepthM,
        stand_type: form.stand_type,
        raw_brief_text: form.raw_brief_text,
        project_budget: parseFloat(form.project_budget) || 0,
        default_margin_pct: parseFloat(form.margin_pct) || 20,
        default_contingency_pct: parseFloat(form.contingency_pct) || 5,
        default_vat_pct: parseFloat(form.vat_pct) || 20,
        parsed_brief_json: parsedBrief || null,
      };

      const project = await api.post('/projects', payload);
      navigate(`/projects/${project.id}`);
    } catch (err) {
      alert('Failed to create project: ' + err.message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto">
      <h1 className="text-2xl font-bold text-gray-900 mb-2">Create New Project</h1>
      <p className="text-sm text-gray-500 mb-8">Set up your exhibition project step by step</p>

      {/* Step Indicator */}
      <div className="flex items-center mb-10">
        {STEPS.map((label, i) => (
          <React.Fragment key={label}>
            <div className="flex items-center">
              <div
                className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-medium ${
                  i < step ? 'bg-brand-600 text-white' : i === step ? 'bg-brand-600 text-white' : 'bg-gray-200 text-gray-500'
                }`}
              >
                {i < step ? <Check className="w-4 h-4" /> : i + 1}
              </div>
              <span className={`ml-2 text-xs font-medium hidden sm:inline ${i <= step ? 'text-brand-600' : 'text-gray-400'}`}>
                {label}
              </span>
            </div>
            {i < STEPS.length - 1 && (
              <div className={`flex-1 h-0.5 mx-3 ${i < step ? 'bg-brand-600' : 'bg-gray-200'}`} />
            )}
          </React.Fragment>
        ))}
      </div>

      {/* Step Content */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-8 mb-8">
        {step === 0 && <StepTier form={form} set={set} />}
        {step === 1 && <StepEventDetails form={form} set={set} />}
        {step === 2 && <StepStandConfig form={form} set={set} />}
        {step === 3 && (
          <StepBrief form={form} set={set} onParse={handleParseBrief} parsing={parsing} parsedBrief={parsedBrief} setParsedBrief={setParsedBrief} />
        )}
        {step === 4 && <StepFinancials form={form} set={set} />}
      </div>

      {/* Navigation */}
      <div className="flex justify-between">
        <button
          onClick={() => step > 0 && setStep(step - 1)}
          disabled={step === 0}
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium text-gray-700 bg-white border border-gray-300 hover:bg-gray-50 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
        >
          <ChevronLeft className="w-4 h-4" />
          Back
        </button>
        {step < STEPS.length - 1 ? (
          <button
            onClick={() => canNext() && setStep(step + 1)}
            disabled={!canNext()}
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium text-white bg-brand-600 hover:bg-brand-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
          >
            Next
            <ChevronRight className="w-4 h-4" />
          </button>
        ) : (
          <button
            onClick={handleSubmit}
            disabled={submitting}
            className="inline-flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-medium text-white bg-brand-600 hover:bg-brand-700 disabled:opacity-60 transition-colors"
          >
            {submitting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
            {submitting ? 'Creating...' : 'Create Project'}
          </button>
        )}
      </div>
    </div>
  );
}

function StepTier({ form, set }) {
  return (
    <div>
      <h2 className="text-lg font-semibold text-gray-900 mb-1">Choose Your Tier</h2>
      <p className="text-sm text-gray-500 mb-6">Select the service level that fits your event</p>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {TIERS.map((tier) => (
          <button
            key={tier.key}
            onClick={() => set('tier', tier.key)}
            className={`text-left p-5 rounded-lg border-2 transition-all ${
              form.tier === tier.key ? tier.selectedColor : tier.color + ' hover:border-gray-400'
            }`}
          >
            <h3 className="font-semibold text-gray-900 mb-2">{tier.name}</h3>
            <p className="text-xs text-gray-600 leading-relaxed">{tier.description}</p>
          </button>
        ))}
      </div>
    </div>
  );
}

function StepEventDetails({ form, set }) {
  return (
    <div>
      <h2 className="text-lg font-semibold text-gray-900 mb-1">Event Details</h2>
      <p className="text-sm text-gray-500 mb-6">Tell us about the event</p>
      <div className="space-y-5">
        <Field label="Event Name *" value={form.event_name} onChange={(v) => set('event_name', v)} placeholder="e.g. London Tech Expo 2026" />
        <Field label="Event Date *" type="date" value={form.event_date} onChange={(v) => set('event_date', v)} />
        <Field label="Venue Name" value={form.venue_name} onChange={(v) => set('venue_name', v)} placeholder="e.g. ExCeL London" />
        <div className="grid grid-cols-2 gap-4">
          <Field label="Venue City" value={form.venue_city} onChange={(v) => set('venue_city', v)} placeholder="e.g. London" />
          <Field label="Guest Count" type="number" value={form.guest_count} onChange={(v) => set('guest_count', v)} placeholder="Expected visitors" />
        </div>
        <Field label="Venue Address" value={form.venue_address} onChange={(v) => set('venue_address', v)} placeholder="Full address" />
      </div>
    </div>
  );
}

function StepStandConfig({ form, set }) {
  return (
    <div>
      <h2 className="text-lg font-semibold text-gray-900 mb-1">Stand Configuration</h2>
      <p className="text-sm text-gray-500 mb-6">Choose your stand size and type</p>

      <div className="mb-8">
        <label className="block text-sm font-medium text-gray-700 mb-3">Stand Size</label>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          {STAND_SIZES.map((size) => (
            <button
              key={size.key}
              onClick={() => set('stand_size', size.key)}
              className={`p-4 rounded-lg border-2 text-center transition-all ${
                form.stand_size === size.key
                  ? 'border-brand-600 bg-brand-50 ring-2 ring-brand-600'
                  : 'border-gray-200 bg-white hover:border-gray-300'
              }`}
            >
              <div className="text-sm font-semibold text-gray-900">{size.label}</div>
              {size.key !== 'custom' ? (
                <>
                  <div className="text-lg font-bold text-brand-600 mt-1">{size.sqm} sqm</div>
                  <div className="text-xs text-gray-500">{size.desc}</div>
                </>
              ) : (
                <div className="text-xs text-gray-500 mt-1">{size.desc}</div>
              )}
            </button>
          ))}
        </div>
        {form.stand_size === 'custom' && (
          <div className="mt-4 max-w-xs">
            <Field label="Custom Size (sqm)" type="number" value={form.stand_sqm} onChange={(v) => set('stand_sqm', v)} placeholder="Enter square metres" />
          </div>
        )}
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-3">Stand Type</label>
        <div className="flex gap-4">
          {[
            { key: 'shell_scheme', label: 'Shell Scheme', desc: 'Pre-built modular walls and fascia' },
            { key: 'space_only', label: 'Space Only', desc: 'Raw floor space for custom builds' },
          ].map((type) => (
            <button
              key={type.key}
              onClick={() => set('stand_type', type.key)}
              className={`flex-1 p-4 rounded-lg border-2 text-left transition-all ${
                form.stand_type === type.key
                  ? 'border-brand-600 bg-brand-50 ring-2 ring-brand-600'
                  : 'border-gray-200 bg-white hover:border-gray-300'
              }`}
            >
              <div className="text-sm font-semibold text-gray-900">{type.label}</div>
              <div className="text-xs text-gray-500 mt-1">{type.desc}</div>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

function StepBrief({ form, set, onParse, parsing, parsedBrief, setParsedBrief }) {
  return (
    <div>
      <h2 className="text-lg font-semibold text-gray-900 mb-1">Project Brief</h2>
      <p className="text-sm text-gray-500 mb-6">Paste or type your brief and let AI extract the key details</p>
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Raw Brief Text</label>
          <textarea
            value={form.raw_brief_text}
            onChange={(e) => set('raw_brief_text', e.target.value)}
            rows={8}
            className="w-full border border-gray-300 rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500 resize-y"
            placeholder="Paste the client's brief here... Include details about design preferences, branding requirements, furniture needs, AV equipment, etc."
          />
        </div>
        <button
          onClick={onParse}
          disabled={parsing || !form.raw_brief_text.trim()}
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium text-white bg-purple-600 hover:bg-purple-700 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
        >
          {parsing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
          {parsing ? 'Parsing...' : 'Parse with AI'}
        </button>

        {parsedBrief && (
          <div className="mt-6 bg-gray-50 rounded-lg border border-gray-200 p-6">
            <h3 className="text-sm font-semibold text-gray-900 mb-4 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-purple-600" />
              Parsed Brief Results
            </h3>
            <div className="space-y-3">
              {parsedBrief.categories && parsedBrief.categories.length > 0 && (
                <div>
                  <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Categories</label>
                  <div className="flex flex-wrap gap-2 mt-1">
                    {parsedBrief.categories.map((cat, i) => (
                      <span key={i} className="bg-brand-100 text-brand-700 text-xs px-2.5 py-1 rounded-full font-medium">
                        {cat.name || cat}
                      </span>
                    ))}
                  </div>
                </div>
              )}
              {parsedBrief.requirements && (
                <div>
                  <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Requirements</label>
                  <ul className="mt-1 space-y-1">
                    {(Array.isArray(parsedBrief.requirements) ? parsedBrief.requirements : [parsedBrief.requirements]).map((req, i) => (
                      <li key={i} className="text-sm text-gray-700">- {typeof req === 'string' ? req : req.description || JSON.stringify(req)}</li>
                    ))}
                  </ul>
                </div>
              )}
              {parsedBrief.summary && (
                <div>
                  <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Summary</label>
                  <p className="text-sm text-gray-700 mt-1">{parsedBrief.summary}</p>
                </div>
              )}
              {parsedBrief.estimated_budget && (
                <div>
                  <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Estimated Budget</label>
                  <p className="text-sm font-medium text-gray-900 mt-1">{parsedBrief.estimated_budget}</p>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function StepFinancials({ form, set }) {
  return (
    <div>
      <h2 className="text-lg font-semibold text-gray-900 mb-1">Financials</h2>
      <p className="text-sm text-gray-500 mb-6">Set the budget and financial parameters</p>
      <div className="space-y-5">
        <Field label="Project Budget (£)" type="number" value={form.project_budget} onChange={(v) => set('project_budget', v)} placeholder="e.g. 25000" />
        <div className="grid grid-cols-3 gap-4">
          <Field label="Margin %" type="number" value={form.margin_pct} onChange={(v) => set('margin_pct', v)} />
          <Field label="Contingency %" type="number" value={form.contingency_pct} onChange={(v) => set('contingency_pct', v)} />
          <Field label="VAT %" type="number" value={form.vat_pct} onChange={(v) => set('vat_pct', v)} />
        </div>
      </div>
    </div>
  );
}

function Field({ label, type = 'text', value, onChange, placeholder = '' }) {
  return (
    <div>
      <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>
      <input
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full border border-gray-300 rounded-lg px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
      />
    </div>
  );
}

// client-angular/src/app/features/projects/pages/project-create/project-create.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { StepsModule } from 'primeng/steps';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { InputNumberModule } from 'primeng/inputnumber';
import { InputTextareaModule } from 'primeng/inputtextarea';
import { DropdownModule } from 'primeng/dropdown';
import { InputSwitchModule } from 'primeng/inputswitch';
import { MessageModule } from 'primeng/message';
import { MenuItem } from 'primeng/api';
import { ProjectService } from '../../../../core/services/project.service';
import { ClientService } from '../../../../core/services/client.service';
import { AiService } from '../../../../core/services/ai.service';
import { Client, ParsedBrief } from '../../../../core/models';

@Component({
  selector: 'app-project-create',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, StepsModule, ButtonModule, InputTextModule, InputNumberModule, InputTextareaModule, DropdownModule, InputSwitchModule, MessageModule],
  template: `
    <div class="max-w-3xl mx-auto">
      <h1 class="text-2xl font-bold text-gray-900 mb-2">Create New Project</h1>
      <p class="text-sm text-gray-500 mb-8">Set up your exhibition project step by step</p>
      <p-steps [model]="steps" [activeIndex]="step" [readonly]="false" (activeIndexChange)="onStepClick($event)" styleClass="mb-8"></p-steps>

      <!-- Step 0: Tier -->
      <div *ngIf="step===0" class="bg-white rounded-lg border border-gray-200 shadow-sm p-8 mb-8">
        <h2 class="text-lg font-semibold text-gray-900 mb-1">Choose Your Tier</h2>
        <p class="text-sm text-gray-500 mb-6">Select the service level that fits your event</p>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <button *ngFor="let t of tiers" (click)="f.tier=t.key"
            [class]="'text-left p-5 rounded-lg border-2 transition-all '+(f.tier===t.key?'border-brand-600 bg-brand-50 ring-2 ring-brand-600':'border-gray-200 hover:border-gray-300')">
            <h3 class="font-semibold text-gray-900 mb-1">{{t.name}}</h3>
            <p class="text-xs text-gray-500 mb-2">{{t.range}}</p>
            <p class="text-xs text-gray-600 leading-relaxed">{{t.desc}}</p>
          </button>
        </div>
      </div>

      <!-- Step 1: Event -->
      <div *ngIf="step===1" class="bg-white rounded-lg border border-gray-200 shadow-sm p-8 mb-8">
        <h2 class="text-lg font-semibold text-gray-900 mb-6">Event Details</h2>
        <div class="space-y-5">
          <div><label class="block text-sm font-medium text-gray-700 mb-1">Event Name *</label>
            <input pInputText [(ngModel)]="f.event_name" placeholder="e.g. London Tech Expo 2026" class="w-full"/></div>
          <div><label class="block text-sm font-medium text-gray-700 mb-1">Client</label>
            <p-dropdown [options]="clients" [(ngModel)]="f.client_id" optionLabel="name" optionValue="id" placeholder="Select client" [showClear]="true" styleClass="w-full"></p-dropdown></div>
          <div><label class="block text-sm font-medium text-gray-700 mb-1">Event Date *</label>
            <input pInputText [(ngModel)]="f.event_date" placeholder="e.g. June 2026, 1st Tuesday in March" class="w-full"/></div>
          <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-sm font-medium text-gray-700 mb-1">Venue Name</label><input pInputText [(ngModel)]="f.venue_name" class="w-full"/></div>
            <div><label class="block text-sm font-medium text-gray-700 mb-1">Venue City</label><input pInputText [(ngModel)]="f.venue_city" class="w-full"/></div>
          </div>
          <div><label class="block text-sm font-medium text-gray-700 mb-1">Venue Address</label><input pInputText [(ngModel)]="f.venue_address" class="w-full"/></div>
          <div><label class="block text-sm font-medium text-gray-700 mb-1">Guest Count</label>
            <p-inputNumber [(ngModel)]="f.guest_count" [useGrouping]="false" styleClass="w-full"></p-inputNumber></div>
        </div>
      </div>

      <!-- Step 2: Stand -->
      <div *ngIf="step===2" class="bg-white rounded-lg border border-gray-200 shadow-sm p-8 mb-8">
        <h2 class="text-lg font-semibold text-gray-900 mb-6">Stand Configuration</h2>
        <label class="block text-sm font-medium text-gray-700 mb-3">Stand Size</label>
        <div class="grid grid-cols-2 md:grid-cols-5 gap-3 mb-6">
          <button *ngFor="let s of sizes" (click)="f.stand_size=s.key"
            [class]="'p-4 rounded-lg border-2 text-center transition-all '+(f.stand_size===s.key?'border-brand-600 bg-brand-50 ring-2 ring-brand-600':'border-gray-200 hover:border-gray-300')">
            <div class="text-sm font-semibold text-gray-900">{{s.label}}</div>
            <div class="text-lg font-bold text-brand-600 mt-1" *ngIf="s.key!=='custom'">{{s.sqm}} m²</div>
            <div class="text-xs text-gray-500">{{s.desc}}</div>
          </button>
        </div>
        <div *ngIf="f.stand_size==='custom'" class="grid grid-cols-2 gap-4 max-w-sm mb-6">
          <div><label class="block text-sm font-medium text-gray-700 mb-1">Width (m)</label>
            <p-inputNumber [(ngModel)]="f.stand_width_m" [minFractionDigits]="1" styleClass="w-full"></p-inputNumber></div>
          <div><label class="block text-sm font-medium text-gray-700 mb-1">Depth (m)</label>
            <p-inputNumber [(ngModel)]="f.stand_depth_m" [minFractionDigits]="1" styleClass="w-full"></p-inputNumber></div>
        </div>
        <label class="block text-sm font-medium text-gray-700 mb-3">Stand Type</label>
        <div class="flex gap-4">
          <button *ngFor="let t of standTypes" (click)="f.stand_type=t.key"
            [class]="'flex-1 p-4 rounded-lg border-2 text-left transition-all '+(f.stand_type===t.key?'border-brand-600 bg-brand-50 ring-2 ring-brand-600':'border-gray-200 hover:border-gray-300')">
            <div class="text-sm font-semibold text-gray-900">{{t.label}}</div>
            <div class="text-xs text-gray-500 mt-1">{{t.desc}}</div>
          </button>
        </div>
      </div>

      <!-- Step 3: Brief -->
      <div *ngIf="step===3" class="bg-white rounded-lg border border-gray-200 shadow-sm p-8 mb-8">
        <h2 class="text-lg font-semibold text-gray-900 mb-6">Project Brief</h2>
        <textarea pInputTextarea [(ngModel)]="f.raw_brief_text" [rows]="8" class="w-full mb-4" placeholder="Paste the client's brief here..."></textarea>
        <p-button icon="pi pi-sparkles" label="{{parsing?'Parsing...':'Parse with AI'}}" severity="help" [disabled]="parsing||!f.raw_brief_text" (click)="parseBrief()" [loading]="parsing"></p-button>
        <div *ngIf="parsed" class="mt-6 bg-gray-50 rounded-lg border border-gray-200 p-6">
          <h3 class="text-sm font-semibold text-gray-900 mb-4"><i class="pi pi-sparkles text-purple-600 mr-2"></i>Parsed Results</h3>
          <div *ngIf="parsed.suggested_categories?.length" class="mb-3">
            <label class="text-xs font-medium text-gray-500 uppercase">Categories</label>
            <div class="flex flex-wrap gap-2 mt-1">
              <span *ngFor="let c of parsed.suggested_categories" class="bg-brand-100 text-brand-700 text-xs px-2.5 py-1 rounded-full font-medium">{{c}}</span>
            </div>
          </div>
          <div *ngIf="parsed.ai_hints" class="mb-3"><label class="text-xs font-medium text-gray-500 uppercase">AI Hints</label><p class="text-sm text-gray-700 mt-1">{{parsed.ai_hints}}</p></div>
          <p-message *ngIf="parsed.missing_fields?.length" severity="warn" [text]="'Missing: '+parsed.missing_fields!.join(', ')"></p-message>
        </div>
      </div>

      <!-- Step 4: Financials -->
      <div *ngIf="step===4" class="bg-white rounded-lg border border-gray-200 shadow-sm p-8 mb-8">
        <h2 class="text-lg font-semibold text-gray-900 mb-6">Financials</h2>
        <div class="space-y-5">
          <div><label class="block text-sm font-medium text-gray-700 mb-1">Project Budget (£)</label>
            <p-inputNumber [(ngModel)]="f.project_budget" mode="currency" currency="GBP" locale="en-GB" styleClass="w-full"></p-inputNumber></div>
          <div><label class="block text-sm font-medium text-gray-700 mb-1">Share budget with suppliers</label>
            <p-inputSwitch [(ngModel)]="f.share_budget"></p-inputSwitch></div>
          <div class="grid grid-cols-3 gap-4">
            <div><label class="block text-sm font-medium text-gray-700 mb-1">Margin %</label><p-inputNumber [(ngModel)]="f.margin" suffix="%" styleClass="w-full"></p-inputNumber></div>
            <div><label class="block text-sm font-medium text-gray-700 mb-1">Contingency %</label><p-inputNumber [(ngModel)]="f.contingency" suffix="%" styleClass="w-full"></p-inputNumber></div>
            <div><label class="block text-sm font-medium text-gray-700 mb-1">VAT %</label><p-inputNumber [(ngModel)]="f.vat" suffix="%" styleClass="w-full"></p-inputNumber></div>
          </div>
        </div>
      </div>

      <div class="flex justify-between">
        <p-button icon="pi pi-chevron-left" label="Back" [outlined]="true" [disabled]="step===0" (click)="step=step-1"></p-button>
        <p-button *ngIf="step<4" icon="pi pi-chevron-right" iconPos="right" label="Next" [disabled]="!canNext()" (click)="step=step+1"></p-button>
        <p-button *ngIf="step===4" icon="pi pi-check" label="{{submitting?'Creating...':'Create Project'}}" [disabled]="submitting" (click)="submit()" [loading]="submitting"></p-button>
      </div>
    </div>
  `
})
export class ProjectCreateComponent implements OnInit {
  step = 0;
  submitting = false;
  parsing = false;
  parsed: ParsedBrief | null = null;
  clients: Client[] = [];
  steps: MenuItem[] = [{ label: 'Tier' }, { label: 'Event' }, { label: 'Stand' }, { label: 'Brief' }, { label: 'Financials' }];
  tiers = [
    { key: 'starter', name: 'Starter', range: '£3k – £15k', desc: 'Shell scheme setup with essential furnishings.' },
    { key: 'professional', name: 'Professional', range: '£15k – £50k', desc: 'Custom build with graphics, lighting and AV.' },
    { key: 'premium', name: 'Premium', range: '£50k+', desc: 'Bespoke design with premium materials and full service.' },
  ];
  sizes = [
    { key: 'small', label: 'Small', sqm: 9, desc: '3×3m', w: 3, d: 3 },
    { key: 'medium', label: 'Medium', sqm: 24, desc: '6×4m', w: 6, d: 4 },
    { key: 'large', label: 'Large', sqm: 54, desc: '9×6m', w: 9, d: 6 },
    { key: 'xl', label: 'XL', sqm: 108, desc: '12×9m', w: 12, d: 9 },
    { key: 'custom', label: 'Custom', sqm: 0, desc: 'Enter size', w: 0, d: 0 },
  ];
  standTypes = [
    { key: 'shell_scheme', label: 'Shell Scheme', desc: 'Pre-built modular walls and fascia' },
    { key: 'space_only', label: 'Space Only', desc: 'Raw floor space for custom builds' },
  ];
  f: any = { tier: '', event_name: '', client_id: null, event_date: '', venue_name: '', venue_city: '', venue_address: '', guest_count: null, stand_size: '', stand_type: 'shell_scheme', stand_width_m: null, stand_depth_m: null, raw_brief_text: '', project_budget: null, share_budget: false, margin: 20, contingency: 5, vat: 20 };

  constructor(private router: Router, private projectSvc: ProjectService, private clientSvc: ClientService, private aiSvc: AiService) {}
  ngOnInit() { this.clientSvc.getAll().subscribe({ next: d => this.clients = d }); }
  onStepClick(i: number) { if (i <= this.step) this.step = i; }
  canNext(): boolean {
    if (this.step === 0) return !!this.f.tier;
    if (this.step === 1) return !!this.f.event_name && !!this.f.event_date;
    if (this.step === 2) return !!this.f.stand_size;
    return true;
  }
  parseBrief() {
    this.parsing = true;
    this.aiSvc.parseBrief(this.f.raw_brief_text).subscribe({ next: d => { this.parsed = d; this.parsing = false; }, error: () => this.parsing = false });
  }
  submit() {
    this.submitting = true;
    const sz = this.sizes.find(s => s.key === this.f.stand_size);
    const w = this.f.stand_size === 'custom' ? this.f.stand_width_m : sz?.w;
    const d = this.f.stand_size === 'custom' ? this.f.stand_depth_m : sz?.d;
    this.projectSvc.create({
      name: this.f.event_name, tier: this.f.tier, event_name: this.f.event_name, client_id: this.f.client_id || undefined,
      event_date: this.f.event_date, venue_name: this.f.venue_name, venue_city: this.f.venue_city, venue_address: this.f.venue_address,
      guest_count: this.f.guest_count, stand_size: this.f.stand_size, stand_width_m: w, stand_depth_m: d, stand_type: this.f.stand_type,
      raw_brief_text: this.f.raw_brief_text, parsed_brief_json: this.parsed || undefined,
      project_budget: this.f.project_budget, share_budget_with_suppliers: this.f.share_budget,
      default_margin_pct: this.f.margin, default_contingency_pct: this.f.contingency, default_vat_pct: this.f.vat,
    }).subscribe({ next: p => this.router.navigate(['/projects', p.id]), error: () => this.submitting = false });
  }
}
