// client/src/layouts/Sidebar.jsx
import React, { useState, useEffect } from 'react';
import { NavLink } from 'react-router-dom';
import { LayoutDashboard, FolderKanban, Truck, Users, Settings, Circle } from 'lucide-react';
import { api } from '../lib/api';

const navItems = [
  { to: '/', label: 'Dashboard', icon: LayoutDashboard, end: true },
  { to: '/projects', label: 'Projects', icon: FolderKanban },
  { to: '/suppliers', label: 'Suppliers', icon: Truck },
  { to: '/clients', label: 'Clients', icon: Users },
  { to: '/settings', label: 'Settings', icon: Settings },
];

export default function Sidebar() {
  const [ballsBalance, setBallsBalance] = useState(null);

  useEffect(() => {
    api.get('/org/balls-balance')
      .then((data) => setBallsBalance(data.balance ?? data.balls_balance ?? 0))
      .catch(() => setBallsBalance(0));
  }, []);

  return (
    <aside className="fixed left-0 top-0 bottom-0 w-64 bg-white border-r border-gray-200 flex flex-col z-40">
      {/* Brand */}
      <div className="px-6 py-5 border-b border-gray-200">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 bg-brand-600 rounded-lg flex items-center justify-center">
            <Circle className="w-5 h-5 text-white fill-white" />
          </div>
          <div>
            <h1 className="text-lg font-bold text-gray-900">The Ballpark</h1>
          </div>
        </div>
      </div>

      {/* Balls Balance */}
      <div className="px-6 py-3 border-b border-gray-200">
        <div className="flex items-center gap-2 text-sm font-medium text-gray-700">
          <span>🔵</span>
          <span>{ballsBalance !== null ? `${ballsBalance} Balls` : 'Loading...'}</span>
        </div>
      </div>

      {/* Navigation */}
      <nav className="flex-1 px-3 py-4 space-y-1 overflow-y-auto">
        {navItems.map((item) => (
          <NavLink
            key={item.to}
            to={item.to}
            end={item.end}
            className={({ isActive }) =>
              `flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors ${
                isActive
                  ? 'bg-brand-50 text-brand-600'
                  : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
              }`
            }
          >
            <item.icon className="w-5 h-5" />
            {item.label}
          </NavLink>
        ))}
      </nav>

      {/* Footer */}
      <div className="px-6 py-4 border-t border-gray-200">
        <p className="text-xs text-gray-400">The Ballpark v1.0</p>
      </div>
    </aside>
  );
}

// client-angular/src/app/layout/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { OrgService } from '../core/services/org.service';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <aside class="fixed left-0 top-0 bottom-0 w-64 bg-white border-r border-gray-200 flex flex-col z-40">
      <div class="px-6 py-5 border-b border-gray-200">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 bg-brand-600 rounded-lg flex items-center justify-center">
            <i class="pi pi-circle-fill text-white text-sm"></i>
          </div>
          <h1 class="text-lg font-bold text-gray-900">The Ballpark</h1>
        </div>
      </div>
      <div class="px-6 py-3 border-b border-gray-200">
        <div class="flex items-center gap-2 text-sm font-medium text-gray-700">
          <span>&#x1F535;</span>
          <span>{{ ballsBalance !== null ? ballsBalance + ' Balls' : 'Loading...' }}</span>
        </div>
      </div>
      <nav class="flex-1 px-3 py-4 space-y-1 overflow-y-auto">
        <a *ngFor="let item of navItems" [routerLink]="item.route" routerLinkActive="bg-brand-50 text-brand-600"
           [routerLinkActiveOptions]="{exact: item.exact || false}"
           class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors text-gray-600 hover:bg-gray-50 hover:text-gray-900">
          <i [class]="'pi ' + item.icon + ' text-lg'"></i>{{ item.label }}
        </a>
      </nav>
      <div class="px-6 py-4 border-t border-gray-200"><p class="text-xs text-gray-400">The Ballpark v1.0</p></div>
    </aside>
  `
})
export class SidebarComponent implements OnInit {
  ballsBalance: number | null = null;
  navItems = [
    { label: 'Dashboard', icon: 'pi-th-large', route: '/', exact: true },
    { label: 'Projects', icon: 'pi-folder', route: '/projects', exact: false },
    { label: 'Suppliers', icon: 'pi-truck', route: '/suppliers', exact: false },
    { label: 'Clients', icon: 'pi-users', route: '/clients', exact: false },
    { label: 'Settings', icon: 'pi-cog', route: '/settings', exact: false },
    { label: 'About', icon: 'pi-info-circle', route: '/about', exact: false },
  ];

  constructor(private orgService: OrgService) {}

  ngOnInit() {
    this.orgService.getBallsBalance().subscribe({
      next: (data) => this.ballsBalance = data.balance ?? 0,
      error: () => this.ballsBalance = 0,
    });
  }
}
